#version: '3.8'

services:
  kelassir-lara-mysql:
    image: mysql:8.0
    container_name: kelassir_lara_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kelassirdb
      MYSQL_USER: sir
      MYSQL_PASSWORD: toor
    volumes:
      - kelassir-mysql_data:/var/lib/mysql
    ports:
      - "8886:3306"
    networks:
      - kelassir-network

  kelassir-lara-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: kelassir_lara_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: sir
      PMA_PASSWORD: toor
    ports:
      - "8888:80"
    networks:
      - kelassir-network

  kelassir-lara-app:
    build:
      context: ./lara/app
      dockerfile: ../Dockerfile
    container_name: kelassir_lara_app
    working_dir: /var/www
    volumes:
      - ./lara/app:/var/www
    networks:
      - kelassir-network

  kelassir-lara-webserver:
    image: nginx:alpine
    container_name: kelassir_lara_nginx_server
    ports:
      - "8880:80"
    volumes:
      - ./lara/app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - kelassir-lara-app
    networks:
      - kelassir-network

volumes:
  kelassir-mysql_data:

networks:
  kelassir-network:
    driver: bridge
