#version: '3.8'

services:
  lara2-mysql:
    image: mysql:8.0
    container_name: kelassir_lara2_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kelassirdb
      MYSQL_USER: sir
      MYSQL_PASSWORD: toor
    volumes:
      - lara2_mysql_data:/var/lib/mysql
    ports:
      - "8886:3306"
    networks:
      - kelassir-lara2-network

  lara2-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: kelassir_lara2_phpmyadmin
    restart: always
    environment:
      PMA_HOST: lara2-mysql
      PMA_USER: sir
      PMA_PASSWORD: toor
    ports:
      - "8888:80"
    networks:
      - kelassir-lara2-network

  lara2-app:
    build:
      context: ./lara/app
      dockerfile: ../Dockerfile
    container_name: kelassir_lara2_app
    working_dir: /var/www
    volumes:
      - ./lara/app:/var/www
      - ./lara/env/env-kelassir-lara:/var/www/.env-kelassir
    networks:
      - kelassir-lara2-network

  lara2-webserver:
    image: nginx:alpine
    container_name: kelassir_lara2_nginx_server
    ports:
      - "8880:80"
    volumes:
      - ./lara/app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lara2-app
    networks:
      - kelassir-lara2-network

volumes:
  lara2_mysql_data:

networks:
  kelassir-lara2-network:
    driver: bridge
